### ISSUE TITLE
/act is working, but /ars is not, and /gfe is odd.

### ISSUE THREAD

**Issue by sjmack** [nmdp-bioinformatics/service-act#12]
I'm using this sequence (A*29:02:01:01 with truncated 5' and 3' UTR sequences that include two 5' and one 3' UTR changes) to test the act operations:

`cgcgtggctctcagagtctcaggccccgaaggcggtgtatggattggggagtcccagccttggggattccccaactccgcagtttcttttctccctctgccaacctatgtagggtccttcttcctggatactcacgacgcggacccagttctcactcccattgggtgtcgggtttccagagaagccaatcagtgtcgtcgcggtcgcggttctaaagtccgcacgcacccaccgggactcagattctccccagacgccgaggatggccgtcatggcgccccgaaccctcctcctgctactcttgggggccctggccctgacccagacctgggcgggtgagtgcggggtcgtggggaaaccgcctctgcggggagaagcaaggggcccgcccggcggggacgcaggacccgggtagccgcgccgggaggagggtcgggtgggtctcagccactcctcgcccccaggctcccactccatgaggtatttcaccacatccgtgtcccggcccggccgcggggagccccgcttcatcgccgtgggctacgtggacgacacgcagttcgtgcggtttgacagcgacgccgcgagccagaggatggagccgcgggcaccgtggatagagcaggaggggccggagtattgggacctgcagacacggaatgtgaaggcccagtcacagactgaccgagcgaacctggggaccctgcgcggctactacaaccagagcgaggccggtgagtgaccccggcccggggcgcaggtcacgacctctcatcccccacggacgggccgggtcgcccacagtctccgggtccgagatccaccccgaagccgcgggaccccgagacccttgccccgggagaggcccaggcgcctttacccggtttcattttcagtttaggccaaaaatccccccgggttggtcggggccggacggggctcgggggactgggctgaccgtggggtcggggccaggttctcacaccatccagatgatgtatggctgcgacgtggggtcggacgggcgcttcctccgcgggtaccggcaggacgcctacgacggcaaggattacatcgccttgaacgaggacctgcgctcttggaccgcggcggacatggcggctcagatcacccagcgcaagtgggaggcggcccgtgtggcggagcagttgagagcctacctggagggcacgtgcgtggagtggctccgcagatacctggagaacgggaaggagacgctgcagcgcacgggtaccgggggccacggggcgcctccctgatcgcctgtagatctcccgggctggcctcccacaaggaggggagacaattgggaccaacactagaatatcgccctccctctggtcctgagggagaggaatcctcctgggtttccagatcctgtaccagagagtgactctgaggttccgccctgctctctgacacaattaagggataaaatctctgaaggaatgacgggaagacgatccctcgaatactgatgagtggttccctttgacacacaccggcagcagccttgggcccgtgacttttcctctcaggccttgttctctgcttcacactcaatgtgtgtgggggtctgagtccagcacttctgagtccctcagcctccactcaggtcaggaccagaagtcgctgttccctcttcagggactagaattttccacggaataggagattatcccaggtgcctgtgtccaggctggtgtctgggttctgtgctcccttccccatcccaggtgtcctgtccattctcaagatagccacatgtgtgctggaggagtgtcccatgacagatgcaaaatgcctgaatgttctgactcttcctgacagacgcccccaagacgcatatgactcaccacgctgtctctgaccatgaggccaccctgaggtgctgggccctgagcttctaccctgcggagatcacactgacctggcagcgggatggggaggaccagacccaggacacggagcttgtggagaccaggcctgcaggggatggaaccttccagaagtgggcgtctgtggtggtgccttctggacaggagcagagatacacctgccatgtgcagcatgagggtctgcccaagcccctcaccctgagatggggtaaggagggagatgggggtgtcatgtcttttagggaaagcaggagcctctctgacctttagcagggtcagggcccctcaccttcccctcttttcccagagccgtcttcccagcccaccatccccatcgtgggcatcattgctggcctagttctctttggagctgtgttcgctggagctgtggtcgctgctgtgaggtggaggaggaagagctcaggtggggtgaagggatgaagggtgggtctgagatttcttgtctcactgagggttccaagacccaggtagaagtgtgccctgcctcgttactgggaagcaccatccacaattatgggcctacccagcctgggccctgtgtgccagcacttactcttttgtaaagcacctgttaaaatgaaggacagatttatcaccttgattacggcggtgatgggacctgatcccagcagtcacaagtcacaggggaaggtccctgaggaccttcaggagggcggttggtccaggacccacacctgctttcttcatgtttcctgatcccgccctgggtctgcagtcacacatttctggaaacttctctgaggtccaagacttggaggttcctctaggaccttaaggccctggctcctttctggtatctcacaggacattttcttcccacagatagaaaaggagggagctactctcaggctgcaagtaagtatgaaggaggctgatgcctgaggtccttgggatattgtgtttgggagcccgtgggggagctcacccaccccacaattcctcctctagccacatcttctgtgggatctgaccaggttctgtttttgtcctaccccaggcagtgacagtgcccagggctctgatatgtctctcacagcttgtaaaggtgagagcctggagggcctgatgtgtgttgggtgttgggcggaacagtggacgcagctgtgctatggggtttctttgcattggatgtattgagcatgcgatgggctgtttaaagtgtgactcctcactgtgacagatacgaatttgttcatgaatatttttttctatagtgtgagacagctgccttgtgtgggactgagaggcaagatttgttcctgcccttccctttgtgacttgaagaaccctgactttgtttctgcaaaggcacctgcatgtgtctgtgttcttgtaggcataatgtgaggaggtggggagaccaccccacccccatgtccaccatgaccctcttcccacgctgacctgtgctccctccccaatcatctttcctgttccagagaggtggggctgaggtgtctccatctctgtctc`

/act  identifies this sequence as HLA-A*29:02:01:01, and assigns it the GFE notation HLA-Aw361-8-12-45-19-65-15-10-7-9-12-2-3-2-4-1-170. 

The sequence for HLA-A*29:02:01:01 in IMGT/HLA Database version 3.28.0 is assigned the GFE notation HLA-Aw332-8-12-45-19-65-15-10-7-9-12-2-3-2-4-1-24.

However, when put either of these notations in /ars with group defined as "G_GROUP", I don't get a G group returned, even though both should return A*29:02:01G.

```
Request URL
http://act.b12x.org/ars?allele=HLA-Aw332-8-12-45-19-65-15-10-7-9-12-2-3-2-4-1-24&group=G_GROUP&verbose=true
Response Body
{
  "allele": "HLA-Aw332-8-12-45-19-65-15-10-7-9-12-2-3-2-4-1-24",
  "group": "",
  "group_type": "G_GROUP",
  "version": "0.0.1"
}
Response Code
200
```

When I use /gfe and submit HLA-A*29:02:01:01, I get the following, which I don't understand.
```
Request URL
http://act.b12x.org/gfe?hla=HLA-A*29%3A02%3A01%3A01
Response Body
{
  "gfe": "HLA-A*29:02:01:01",
  "hla": [
    "HLA-Aw52-8-12-45-19-65-15-10-7-9-12-2-3-2-4-1-24",
    "HLA-Aw332-8-12-45-19-65-15-10-7-9-12-2-3-2-4-1-24"
  ],
  "version": "0.0.1"
}
Response Code
200
```
Why is /gfe returing two GFE notations? Both of these notations return HLA-A*29:02:01:01 in /hla, but HLA-Aw361-8-12-45-19-65-15-10-7-9-12-2-3-2-4-1-170 does not. 

Both of the GFE notations returned by /gfe return the same sequence from /sequence, so it seems like the sequence of HLA 5'UTR indexes 52 and 332 are the same; how can that happen? Shouldn't service-feature have recognized a second submission of that sequence as 52?

**Comment by mmaiers-nmdp** [comment]
The behavior wrt UTRs is that it doesn't seem to include them in the comparison.  By mutating other introns and exons (outside of ARD exons) the /act returns HLA-A*29:02:01:01 as well.  It must be matching on ARD exons only.

**Comment by mmaiers-nmdp** [comment]
The labels ("gfe" and "hla") in the response to /gfe are backward "gfe": "HLA-A*29:02:01:01",
  "hla": [
    "HLA-Aw52-8-12-45-19-65-15-10-7-9-12-2-3-2-4-1-24",
    "HLA-Aw332-8-12-45-19-65-15-10-7-9-12-2-3-2-4-1-24"
  ],

**Comment by mhalagan** [comment]
> /act identifies this sequence as HLA-A*29:02:01:01, and assigns it the GFE notation HLA-Aw361-8-12-45-19-65-15-10-7-9-12-2-3-2-4-1-170. The sequence for HLA-A*29:02:01:01 in IMGT/HLA Database version 3.28.0 is assigned the GFE notation HLA-Aw332-8-12-45-19-65-15-10-7-9-12-2-3-2-4-1-24. However, when put either of these notations in /ars with group defined as "G_GROUP", I don't get a G group returned, even though both should return A*29:02:01G.

The "/ars" API is broken at the moment. It only works for HLA alleles and hasn't been updated to work with GFE yet. Thanks for pointing this out.

> Why is /gfe returing two GFE notations? Both of these notations return HLA-A*29:02:01:01 in /hla, but HLA-Aw361-8-12-45-19-65-15-10-7-9-12-2-3-2-4-1-170 does not. Both of the GFE notations returned by /gfe return the same sequence from /sequence, so it seems like the sequence of HLA 5'UTR indexes 52 and 332 are the same; how can that happen? Shouldn't service-feature have recognized a second submission of that sequence as 52?

There's one GFE that's derived directly from the coordinates in IMGT and another that's created by using the annotation pipeline. If you query the graph there are both expected and observed edges to GFE nodes.

> but HLA-Aw361-8-12-45-19-65-15-10-7-9-12-2-3-2-4-1-170 does not.

The "/hla" API is only using the expected GFE in the graph and isn't doing any computational comparisons. That means if the GFE you submit to the "/hla" API doesn't match the expected GFE (HLA-Aw52-8-12-45-19-65-15-10-7-9-12-2-3-2-4-1-24) then it won't return any HLA alleles. It needs to be updated to perform the same operations as the "/act" API when the GFE doesn't exist in the graph. 

@mmaiers-nmdp, I believe those labeling errors have been fixed, but the latest Docker image may not have been deployed to act.b12x.org yet. I'm working on putting together a development pipeline that would automate this.



Thanks,
Mike

**Comment by sjmack** [comment]
@mhalagan-nmdp, I can't query the graph because I don't know what the url is, and I don't have a userID or password. How do I get such things?

It seems like generating two separate GFEs -- one for IMGT/HLA releases and a second for pipeline-derived sequences -- defeats the purpose of annotation. Shouldn't IMGT/HLA sequence information be parsed via the pipeline to prevent duplication?

**Comment by mhalagan** [comment]
@sjmack 

I've updated the ACT (act.b12x.org) and GFE (gfe.b12x.org) services.

The ACT service now does the following:
- Class II and KIR can now be typed
- The closest IHIW reference allele is returned as ihiw_ref
- Returns a more detailed data structure that includes the features of the annotated GFE and what features are shared with the allele that it's being called as.
- The /act_format API allows the user to have the data returned in plain text as any BioPython format (ex. imgt, embl, genebank, fastq, etc). The ID in the returned file will be the full gene accession number.
- The /feature_search API allows users to search for alleles and GFE that share specific features of given allele or alleles (ex. What alleles share exons 2, 3 and 4 with HLA-A*01:01:01:01?)
- ARS works for both GFE and HLA alleles and returns a more detailed data structure

If you're passing really large sequences for KIR or class II then it won't work on act.b12x.org, but it will if you're running it locally. I'm not using elastic beanstalk for the GFE service anymore, so tomorrow I should be able to figure out the post size limit that's causing it to crash.

When you have a chance give it a try and let me know what you think.

**Comment by mhalagan** [comment]
@sjmack 

> It seems like generating two separate GFEs -- one for IMGT/HLA releases and a second for pipeline-derived sequences -- defeats the purpose of annotation. Shouldn't IMGT/HLA sequence information be parsed via the pipeline to prevent duplication?

There aren't always two GFEs for one HLA allele. There are only two when the expected GFE (taken from the exact coordinates from IMGT/HLA) differs from the observed (generated with the GFE service and annotation pipeline). These are often three base pair differences, where the codon is added to the next exon or taken from it (ex. three base pairs from the end of exon 4 are added to the beginning of exon 5).  It's useful to persist both of these because it helps with the ACT making allele calls. Sequences submitted may match parts of sequences from both observed and expected GFE, and without both persisted it may be difficult to make an allele call. The more data that's persisted in the GFE DB, the more accurate it becomes at typing HLA alleles. If I persisted the sequences and typings of the 30,000k subjects I ran through for the abstract, then it would get all of them correct the next time around.

The original issue that was pointed out has been fixed (see below results) so I'm going to close this issue. Please open a new issue if you find anything else.

`curl -X GET --header 'Accept: application/json' 'http://act.b12x.org/ars?allele=HLA-Aw332-8-12-45-19-65-15-10-7-9-12-2-3-2-4-1-24&group=G_GROUP'`

```JSON
{
  "act_version": "0.0.3",
  "allele": "HLA-Aw332-8-12-45-19-65-15-10-7-9-12-2-3-2-4-1-24",
  "gfedb_version": "0.0.2",
  "group": "A*29:02:01G",
  "group_type": "G_GROUP",
  "share_allele": [
    {
      "hla": "HLA-A*29:02:01:01"
    }
  ]
}
```
