### ISSUE TITLE
Submitting large sequences fails: 414 Request-URI Too Large

### ISSUE THREAD

**Issue by bmatern** [nmdp-bioinformatics/service-act#43]
I am attempting to annotate a DRB1 sequence. DRB sequences are apparently too large. The /annotate method returns this response:

```
<html>
<head><title>414 Request-URI Too Large</title></head>
<body bgcolor="white">
<center><h1>414 Request-URI Too Large</h1></center>
<hr><center>nginx/1.15.2</center>
</body>
</html>
```

The limit apparently is somewhere between 7500 and 10000 base.  I am attaching 2 sample files here, 
The DQB1 allele (7481 bp) annotates successfully but the DRB1 allele (10965 bp) fails.

[DQB1_020101.txt](https://github.com/nmdp-bioinformatics/service-act/files/2469430/DQB1_020101.txt)
[DRB1_010301.txt](https://github.com/nmdp-bioinformatics/service-act/files/2469431/DRB1_010301.txt)

This suggests that the default in Apache is 8190 characters, maybe useful.

https://stackoverflow.com/questions/2891574/how-do-i-resolve-a-http-414-request-uri-too-long-error

**Comment by pbashyal-nmdp** [comment]
Parameters to `GET` requests are of limited length. Any API call that takes a sequence should be a `POST` request.

**Comment by mmaiers-nmdp** [comment]
The act interface is deprecated.  Move to gfe-service.

**Comment by bmatern** [comment]
Resolved in GFE Service.
